server:
  listen:
    - address: 4974
    - address: 4975
      cert-file:
      key-file:
      auto-cert: 1
  verbose: 0
backends:
  targets:
    - server: "localhost:8080"
      type: http
    - server: "www.myproxy.com:8080"
      type: http
      username:
      password:
  targets-from-document:
    - file-path: ./sample.txt
      url:
      extract-type: script # delimiter, script, disabled
      delimiter:
      type:
      script-entrance: extract
      extract-script: >
        function extract(doc) {
          var regex = /host=([\d\.]+)&port=(\d+)/g;
          var matched = doc.matchAll(regex);
          var result = [];
          for (const element of matched) {
            var proxy = {"type":"http", "server": `${element[1]}:${element[2]}`};
            result.push(proxy);
          }
          return result;
        }
health:
  health-interval: 30s
  health-timeout: 10s
  health-url: https://www.google.com
  health-response-status: 2xx
  threads: 10   # 0 means unlimited
  user-agent: "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/92.0.4515.159 Safari/537.36"
selector: minimum-response-duaration # only minimum-response-duaration is supported, todo for random, round-robin