server:
  pprof: 4949
  listen:
    - address: 4974
  verbose: 0
backends:
  targets:
    - server: "localhost:8580"
      type: http
health:
  health-interval: 30s
  health-timeout: 10s
  health-url: https://www.google.com
  health-response-status: 2xx
  threads: 10   # 0 means unlimited
  user-agent: "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/109.0.0.0 Safari/537.36"
selector: minimum-response-duration # only minimum-response-duration is supported, todo for random, round-robin